#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run tests
bun test

# Run linting
bunx eslint . --fix

# Run formatting
prettier $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g') --write --ignore-unknown
git update-index --again
